name: bicrew
description: 'Speedometer application that can communicate with gestures when riding a bicycle with a crew.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7
  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2
  dual_screen: ^1.0.4
  google_fonts: ^6.1.0
  intl: ^0.18.1
  rally_assets: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - packages/flutter_gallery_assets/assets/studies/rally_card_dark.png
  - packages/flutter_gallery_assets/assets/studies/rally_card.png
  - packages/rally_assets/logo.png
  - packages/rally_assets/thumb.png
